language: ruby
rvm:
  - 1.9.3
  - 2.0.0
before_script:
  - psql -c 'create database bitcoin_test;' -U postgres
  - mysql -e 'create database bitcoin_test;'
env:
  - TEST_DB_POSTGRES="postgres://postgres@localhost/bitcoin_test"
  - TEST_DB_MYSQL="mysql:/bitcoin_test"